spring:
  rabbitmq:
    addresses: 192.168.150.129:5672
    username: guest
    password: guest
    host: /
    connection-timeout: 15000
  http:
    encoding:
      charset: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL

server:
  port: 8001
  servlet:
    context-path: /prudocer

